import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
data= pd.read_csv('Combined Bond Indices  Yields.csv')
data.drop(['Unnamed: 0'], inplace=True, axis=1)
print(data.columns)
new_data = data.select_dtypes(include=['number'])
print(new_data.kurt())      
fig, ax=plt.subplots(figsize=(9,8))
plt.title(label="Corporate Bonds Total Return (TR) Correlation Matrix")
collist=["US_AAA_TR","US_AA_TR","US_A_TR","US_BBB_TR","US_BB_TR","US_B_TR","US_CCC_TR"]
mask=np.triu(new_data[collist].corr())
sns.heatmap(new_data[collist].corr(),annot=True,annot_kws={"size": 10},square=True,cmap="coolwarm",fmt=".3f",mask=mask)
plt.xticks(rotation=60,horizontalalignment="right")
plt.tight_layout()
plt.show()
fig, ax=plt.subplots(figsize=(10,9))
plt.title(label="Corporate Bonds Total Return (TR) Correlation Matrix")
collist=["US_AAA_TR","US_AA_TR","US_A_TR","US_BBB_TR","US_BB_TR","US_B_TR","US_CCC_TR","EMEA_Gen_TR","EM_Gen_TR","US_Gen_TR"]
mask=np.triu(new_data[collist].corr())
sns.heatmap(new_data[collist].corr(),annot=True,annot_kws={"size": 10},square=True,cmap="coolwarm",fmt=".3f",mask=mask)
ax.add_patch(plt.Rectangle((2,7),2,1,fill=False,lw=2))
ax.add_patch(plt.Rectangle((3,8),1,1,fill=False,lw=2))
ax.add_patch(plt.Rectangle((2,9),2,1,fill=False,lw=2))
plt.axhline(y=7,xmin=0,xmax=0.7,ls="--",c="purple")
plt.axvline(x=7,ymin=0,ymax=0.3,ls="--",c="purple")
plt.xticks(rotation=60,horizontalalignment="right")
plt.tight_layout()
plt.show()
fig, ax=plt.subplots(figsize=(7,6))
plt.title(label="Bond Yield Correlation Matrix")
collist=["US_AAA_Y","US_AA_Y","US_A_Y","US_BBB_Y","US_BB_Y","US_B_Y","US_CCC_Y","US_Gen_Y","US_High_Y","EM_Good_Y","EM_High_Y"]
mask=np.triu(new_data[collist].corr())
sns.heatmap(new_data[collist].corr(),annot=True,annot_kws={"size": 10},square=True,cmap="coolwarm",mask=mask)
ax.add_patch(plt.Rectangle((1,7),3,1,fill=False,lw=2))
ax.add_patch(plt.Rectangle((4,8),2,1,fill=False,lw=2))
ax.add_patch(plt.Rectangle((2,9),2,1,fill=False,lw=2))
ax.add_patch(plt.Rectangle((4,10),3,1,fill=False,lw=2))
plt.axhline(y=7,xmin=0,xmax=0.64,ls="--",c="purple")
plt.axvline(x=7,ymin=0,ymax=0.36,ls="--",c="purple")
plt.xticks(rotation=60,horizontalalignment="right")
plt.tight_layout()
plt.show()
print(new_data[["US_AAA_Y","US_AA_Y","US_A_Y","US_BBB_Y","US_BB_Y","US_B_Y","US_CCC_Y","US_Gen_Y","US_High_Y","EM_Good_Y","EM_High_Y"]].sample(10))
